### ISSUE TITLE
Need help with this issue

### ISSUE THREAD

**Issue by umarservishero** [hodgepodgers/ng-intl-tel-input#39]
TypeError: elm.intlTelInput is not a function
    at Object.create.init.value (http://localhost:3001/ng-intl-tel-input/dist/ng-intl-tel-input.js:21:17)
    at link (http://localhost:3001/ng-intl-tel-input/dist/ng-intl-tel-input.js:44:26)

Any help is much appreciated

**Comment by bighappyface** [comment]
@umarservishero do you have all of the dependencies included in your page? Please review out demo file for an example of what to integrate:

https://github.com/hodgepodgers/ng-intl-tel-input/blob/15f1dda21d946a5acc6bea96babb9f50409f63f7/index.html#L87-L90

**Comment by shenlong** [comment]
Inspect your index for the <script src="..." > The issue is if jquery.js is specify after angular.js, angular will only use their own JQLite which causes Jquery issue.

If you are using task runner like gulp or grunt, make sure that jquery exist above angular. Angular will use JQuery if it is loaded first and present:

    "dependencies": {
      "jquery": ">=2.1.0",
      "angular": "~1.4.7",
    }

**Comment by bighappyface** [comment]
+1 thanks @shenlong

**Comment by MherX** [comment]
Hi, I give error after connect this module in ASP.NET project:

TypeError: elm.intlTelInput is not a function
    at Object.value (http://localhost:5001/Scripts/ng-intl-tel-input.js:27:29)
    at Object.link (http://localhost:5001/Scripts/ng-intl-tel-input.js:51:36)
    at http://localhost:5001/Scripts/angular.js:1247:18
    at invokeLinkFn (http://localhost:5001/Scripts/angular.js:9934:9)
    at nodeLinkFn (http://localhost:5001/Scripts/angular.js:9335:11)
    at compositeLinkFn (http://localhost:5001/Scripts/angular.js:8620:13)
    at compositeLinkFn (http://localhost:5001/Scripts/angular.js:8623:13)
    at compositeLinkFn (http://localhost:5001/Scripts/angular.js:8623:13)
    at nodeLinkFn (http://localhost:5001/Scripts/angular.js:9330:24)
    at compositeLinkFn (http://localhost:5001/Scripts/angular.js:8620:13) <input class="form-control ng-pristine ng-untouched ng-valid" placeholder="Телефон*" name="phone" type="tel" ng-model="newUser.phone" required="" ng-intl-tel-input="" data-initial-country="ge">(anonymous function) @ angular.js:13920

Help please.

**Comment by ahayder** [comment]
Hi, did anyone solved the issue?

**Comment by ahayder** [comment]
Adding jquery before angular worked for me.

**Comment by atifsaddique211f** [comment]
I had to include all the following dependencies in given order for it to work for me.

`<link rel="stylesheet" href="bower_components/intl-tel-input/build/css/intlTelInput.css">`
  `<script src="bower_components/jquery/dist/jquery.js"></script>`
  `<script src="bower_components/angular/angular.js"></script>`
  `<script src="bower_components/ng-intl-tel-input/dist/ng-intl-tel-input.js"></script>`
  `<script src="bower_components/intl-tel-input/build/js/intlTelInput.js"></script>`
  `<script src="bower_components/intl-tel-input/build/js/utils.js"></script>`

**Comment by ido1wald** [comment]
I found a solution.. bad versions :( 
I used intl-tel-input with v 9.0.0 with jquery 1.11.2 and ng-intl-tel-input 2.0.0
Horrible solution but if it works- it works

**Comment by amalmohann** [comment]
Add utils.js in scripts,

    `"scripts": [ 
                  "node_modules/intl-tel-input/build/js/utils.js"
                ]`
    

in angular.json file. This will solve your issue.

 1. goto angular.json file
 2. look for scripts
 3. add "node_modules/intl-tel-input/build/js/utils.js" inside the scripts along with the intlTelInput.min.js / intlTelInput.js
 4. save
 5. refresh your application
